import 'dotenv/config';
import connectDB from '../config/db.js';
import User from '../models/User.js';
import Category from '../models/Category.js';
import Product from '../models/Product.js';
import slugify from 'slugify';

const categories = [{ name: 'Audio', description: 'Immersive sound for every day' }, { name: 'Workspace', description: 'Tools for better focus' }, { name: 'Lifestyle', description: 'Small upgrades, beautifully made' }, { name: 'Travel', description: 'Lightweight essentials for the road' }];
const products = [
 ['Arc headphones','Audio',149,119,'Wireless over-ear headphones with spatial audio','Sonora',42], ['Pebble earbuds','Audio',89,69,'Pocket-sized earbuds with a rich, balanced sound','Sonora',88], ['Field speaker','Audio',129,99,'Water-resistant speaker made for slow afternoons','Sonora',25], ['Studio mic','Workspace',179,149,'A warm, clear USB microphone for calls and creation','Northline',14], ['Orbit lamp','Workspace',79,59,'Adjustable task light with a soft sunrise mode','Luma',31], ['Slate keyboard','Workspace',119,99,'Low-profile mechanical keyboard with quiet switches','Northline',18], ['Canvas desk mat','Workspace',49,39,'Recycled felt mat that makes a desk feel considered','Morrow',64], ['Daily notebook','Lifestyle',24,18,'Lay-flat notebook with 160 pages of archival paper','Morrow',120], ['Glass bottle','Lifestyle',36,28,'Double-wall bottle that keeps water cold for 24 hours','Aster',55], ['Cloud throw','Lifestyle',98,79,'Soft cotton throw for reading corners and quiet nights','Morrow',12], ['Everyday tote','Lifestyle',54,42,'Structured canvas tote with a hidden laptop sleeve','Aster',43], ['Transit pack','Travel',139,109,'Weatherproof 20L pack with a thoughtful interior','Northline',20], ['Packing cubes','Travel',44,34,'Three lightweight cubes for calmer packing','Aster',67], ['Travel adapter','Travel',39,29,'Universal adapter with two USB-C ports','Northline',72], ['Pocket charger','Travel',69,54,'Compact 10,000mAh charger with fast USB-C power','Sonora',38], ['Merino socks','Travel',28,22,'Breathable merino socks for long days outside','Morrow',96], ['Weekender bag','Travel',159,129,'A durable weekender with a separate shoe compartment','Aster',9], ['Desk clock','Lifestyle',62,49,'A quiet, tactile clock for the bedside or desk','Luma',27]
];
async function seed() { await connectDB(); await Promise.all([User.deleteMany(), Category.deleteMany(), Product.deleteMany()]); const createdCategories = await Category.insertMany(categories.map(c => ({ ...c, slug: slugify(c.name, { lower: true }) }))); const lookup = Object.fromEntries(createdCategories.map(c => [c.name, c._id])); await Product.insertMany(products.map(([name, category, price, discountPrice, description, brand, stock], index) => ({ name, slug: `${slugify(name, { lower: true })}-${index}`, category: lookup[category], price, discountPrice, description, brand, stock, rating: 4 + (index % 10) / 10, numReviews: 12 + index, images: [`https://images.unsplash.com/photo-${['1505740420928-5e560c06d30e','1572569511254-d8f925fe2cbb','1608043152269-423dbba4e7e1','1583394838336-acd977736f90'][index % 4]}?auto=format&fit=crop&w=900&q=85`] }))); await User.create([{ name: 'Avery Admin', email: 'admin@nexamarket.com', password: 'Admin123!', role: 'admin' }, { name: 'Demo Customer', email: 'hello@nexamarket.com', password: 'Customer123!', role: 'user' }]); console.log('Seed complete. Admin: admin@nexamarket.com / Admin123!'); process.exit(0); }
seed().catch(error => { console.error(error); process.exit(1); });
